name: Deploy Worker
permissions:
  contents: read

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - '.gitignore'
      - '.editorconfig'
      - '.vscode/**'
      - 'docs/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: Deploy Worker
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ 9tpk6pDpMESuX550yX9SWdwEWpvmC2pUf3fCmu3P }}
          accountId: ${{ 30d9b0a8403f5ca882a9a3577b732150 }}
